---
title: "Roupen Khanjian's Resume"

# styles:
#   colour: blue
#   bg-colour: green
#   header-font: Bitter
output:
  pagedown::html_resume:
    # theme: darkly
    # try to add chrome_print()?
    self_contained: false
    css: "style_default_change.css"
    
---

Aside
================================================================================


Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope" style="color:#ff7a59"></i> roupen@pstat.ucsb.edu
- <i class="fas fa-globe"></i> [personal website](https://khanjian.github.io/roupen-website/)
- <i class="fab fa-linkedin" style="color:#2175ed"></i> [linkedin.com/in/khanjian](https://www.linkedin.com/in/khanjian)
- <i class="fa fa-github" style="color:black"></i>  [github.com/khanjian](https://github.com/khanjian)
- <i class="fas fa-phone" style="color:#003366"></i> (818) 621-5403


Skills {#skills}
--------------------------------------------------------------------------------

- <i class="fab fa-r-project" style="color:#70b8ff"></i> R | <i class="fab fa-python" style="color:#306998"></i> Python  
  <!-- + Tidyverse -->
  <!-- + Shiny -->
  <!-- + Rmarkdown -->
  

- <i class="fas fa-database" style="color:#b5b500" ></i> SQL | <i class="fas fa-file-excel" style="color:#1D6F42"></i> Microsoft Excel 



- <i class="far fa-star" style="color:DarkOrange"></i> Apache Spark | <i class="fa fa-github" style="color:black"></i> Github 


- <i class="fas fa-file-powerpoint"  style="color:#d04423" ></i> Presentations | <i class="fas fa-flask" style="color:#59ff36"></i> Labwork


<!-- - <i class="fas fa-chalkboard-teacher"></i> Teaching  -->

<!-- - հայերեն Fluent in Armenian -->

- Բարեւ աշխարհ
- Fluent in Armenian


Main
================================================================================

Roupen Khanjian {#title}
--------------------------------------------------------------------------------



Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------
### University of California, Santa Barbara (UCSB) 

Master of Arts in Statistics

Santa Barbara, CA  

2021 - 2018

::: concise
- Statistical Data Science <i class="fab fa-python" style="color:#306998"></i>
- Design of Experiments <i class="fab fa-r-project" style="color:#70b8ff"></i> 
- Statistical Machine Learning <i class="fab fa-r-project" style="color:#70b8ff"></i> 
- Advanced Statistical Methods <i class="fab fa-r-project" style="color:#70b8ff"></i> 
- Big Data Analytics <i class="far fa-star" style="color:DarkOrange"></i> <i class="fab fa-python" style="color:#306998"></i>
- Spatial Statistics <i class="fab fa-r-project" style="color:#70b8ff"></i> 
- Time Series Analysis <i class="fab fa-r-project" style="color:#70b8ff"></i> 
- Advanced Data Analysis <i class="fab fa-r-project" style="color:#70b8ff"></i> <i class="fa fa-github" style="color:black"></i>
::: 

### Portland State University 

Post-Baccalaureate  

Portland, OR  							  

2018 - 2017  

::: concise
- Linear Algebra
- Group Theory
- Ordinary Differential Equations
- Mathematical Statistics
::: 

### University of California, Berkeley

Bachelor of Arts in Psychology   
Bachelor of Arts in Molecular and Cell Biology

Berkeley, CA  						            	            

2012 - 2009

::: concise
- Data Analysis in Psychology 
- Cognitive Neuroscience
::: 


<!-- Research Experience {data-icon=laptop} -->
<!-- -------------------------------------------------------------------------------- -->




Teaching Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

### Regression Analysis 

Teaching Assistant (TA) for PSTAT 126 <i class="fab fa-r-project" style="color:#70b8ff"></i>

UCSB  

Spring   
2021  
Winter   
2021  
Winter   
2020  

- Created weekly tutorials on using R to conduct linear regression.
- Aided students troubleshoot and debug R code for homeworks. 


### Statistics for Economics

TA for PSTAT 109 <i class="fas fa-file-excel" style="color:#1D6F42"></i> 

UCSB

Fall  
2020
Summer 2020  
Fall   
2019  
Fall   
2018

- Designed & administered quizzes based off statistical concepts.
- Facilitated weekly Microsoft Excel problem sets.


### Principles of Data Science with R

TA for PSTAT 10 <i class="fab fa-r-project" style="color:#70b8ff"></i> <i class="fas fa-database" style="color:#b5b500" ></i> 

UCSB

Spring 
2020  
Summer 
2019  
Spring 
2019  
Winter 
2019  

- Assisted students in learning statistical programming using R.
- Helped students understand relational database management systems and data manipulation using SQL. 



Projects {data-icon=chart-line} 
--------------------------------------------------------------------------------
### What's in a Word? A Shiny App for Text Analysis

[Final project for ESM 244 (Advanced Data Analysis)](https://khanjian.shinyapps.io/Text_Analysis/) <i class="fas fa-file-powerpoint"  style="color:#d04423" ></i> <i class="fab fa-r-project" style="color:#70b8ff"></i>

UCSB

Winter 2021

**Khanjian R.A.**, Handy, M., Shen R.

### Stop and Frisk in New York City from 2017 - 2019

Final project for PSTAT 234 (Statistical Data Science) <i class="fas fa-file-powerpoint"  style="color:#d04423" ></i> <i class="fab fa-python" style="color:#306998"></i>

UCSB

Spring 2020

**Khanjian R.A.**.


### Dimension Reduction with Karhunen-Lóeve Decomposition, Empirical Orthogonal Function and Maximum Covariance Pattern

Final project for PSTAT 262ST (Spatial Statistics) <i class="fas fa-file-powerpoint"  style="color:#d04423" ></i> <i class="fab fa-r-project" style="color:#70b8ff"></i> 

UCSB

Fall  
2019

**Khanjian R.A.**, Zhang C.


Professional Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

### Video Analyst

Portland Trail Blazers

Portland, Oregon

2017 - 2016


- Tracked statistical data from NBA game tape to help create scouting reports for the Portland Trail Blazers.
<!-- - Trained in efficiently identifying play types such as Post-ups, Off Ball Screens, Pick and Rolls, or Handoffs. -->


### Research Assistant II 	

Oregon Health & Science University (OHSU)

Portland, Oregon

2016 - 2015

- Developed a new protocol to pinpoint which cells in the retina contain Calcium-Permeable AMPA receptors. <i class="fas fa-flask" style="color:#59ff36"></i>  
- Measured fluorescence intensity of the Kv2.2 antibody on photoreceptors with ImageJ; organized data via IgorPro and Excel. <i class="fas fa-file-excel" style="color:#1D6F42"></i> 

::: aside

- Principal Investigator: 
- [Dr. Teresa Puthussery](https://optometry.berkeley.edu/people/teresa-puthussery-od-phd/)

::: 

### Research Assistant II 	

OHSU

Portland, Oregon

2014 - 2013


<!-- - Examined the effects of systemically administered opioids on analgesia, respiratory parameters, and body temperature in lightly anesthetized rodents. -->
- Investigated the contributions of opioid-sensitive neurons in the brainstem using in-vivo single cell electrophysiology. <i class="fas fa-flask" style="color:#59ff36"></i> 


::: aside

- Principal Investigator:    
- [Dr. Mary Heinricher](https://www.ohsu.edu/people/mary-m-heinricher/18BC7EAA23AA4FA9A377AD7F69263067)

::: 

Selected Publications and Posters {data-icon=file}
--------------------------------------------------------------------------------

### Heteromeric Kv2/Kv8.2 channels mediate delayed rectifier potassium currents in primate photoreceptors.

[*JNeurosci; 38: 3414–3427.*](https://doi.org/10.1523/JNEUROSCI.2440-17.2018)

N/A

2018

Gayet-Primo J., Yaeger D.B., **Khanjian R.A.**, Puthussery T.

### Identification of neuronal populations that express calcium permeable AMPA receptors in mouse and macaque retina.

[*Poster for the Association for Research in Vision & Ophthalmology (ARVO) conference.*](https://iovs.arvojournals.org/article.aspx?articleid=2561144) <i class="fas fa-file-powerpoint"  style="color:#d04423" ></i>

Seattle, WA

2016

**Khanjian R.A.**, Puthussery T. 


### Cellular mechanisms of activity-dependent BDNF expression in primary sensory neurons.

[*Neuroscience; 310: 665–673.*](https://doi.org/10.1016/j.neuroscience.2015.10.007)

N/A

2015

Vermehren-Schmaedick A., **Khanjian R.A.**, Balkowiec A.


::: aside

This resume was made with the <i class="fab fa-r-project" style="color:#70b8ff"></i>  package 
[**pagedown**](https://github.com/rstudio/pagedown).

*Last updated on `r Sys.Date()`.*

:::


